### PR TITLE
Issue #19 - Mute stderr output of 'stty size' in get_console_width().

### PR DESCRIPTION
**Pull request by accwebs**
* This silences the 'stty: standard input: Inappropriate ioctl for device' errors.
 * Idea for how to fix this problem shamelessly copied from https://github.com/cmihai/compose/commit/b40104870039763a4f7fce2ca2e37529acad7811

Signed-off-by: Aaron Curley <accwebs@gmail.com>

### CODE REVIEW

**Comment by accwebs** [comment]
I'm terrible at Python, so if you see an easier way to implement the test, feel free to let me know or of course, make edits.

**Comment by accwebs** [comment]
Also, I'm having problems with running the build locally due to (I think) the recently-added test case for the push typo issue.  Plus, it looks like the travis-ci build failed.  Any ideas?

**Comment by avirshup** [comment]
Thanks @accwebs - the code LGTM!

Not sure why travis is failing for this, but I've pushed a few updates that should skip the offending tests when you run them locally. I'll try merging this with those changes and see if it fixes the problems.

**Comment by avirshup** [comment]
Aside from some py2/py3 issues, all looks good. Thanks!

**Pull request merged**
