### PR TITLE
[buildargs] Make the buildargs argument optional

### PR DESCRIPTION
**Pull request by owbear**
+ Fix the expanduser() call
+ Remove debug output
+ Use argparse.FileType() to ensure ArgumentParser flags unreadable files

### CODE REVIEW

**Comment by yoyonel** [comment]
This patch resolve partially the problem, you don't catch any exceptions in your code ... (in my sens) it's not enough (but it's a good beginning).

**Comment by owbear** [comment]
You will get a good error message if a non-existant or unreadable file is specified:

```
➜  example git:(buildargs_fix) ✗ python2 ../docker-make.py -b unreadable-file
usage: docker-make.py [-h] [-f MAKEFILE] [-a] [-l]
                      [--requires [REQUIRES [REQUIRES ...]]] [--name NAME]
                      [-b BUILDARGS] [-p] [-n] [--pull] [--no-cache]
                      [--repository REPOSITORY] [--tag TAG]
                      [--push-to-registry] [--help-yaml]
                      [TARGETS [TARGETS ...]]
docker-make.py: error: argument -b/--buildargs: can't open 'unreadable-file': [Errno 2] No such file or directory: 'unreadable-file'
```

**Comment by yoyonel** [comment]
Oki i see. Nice solution i didnt kown this trick. Thanks you ^^

**Comment by owbear** [comment]
New pull request incoming

**Pull request closed without merging**
